-- Mirror class AFFS.
AFFS.mirroredMap = {
    mortalterror = "conviction",
    eluded = "distortion",
    fae_curse = "farag_rot",
    debilitated = "glasslimb",
    unspooled = "leeched_aura",
    lurk = "penance",
    aftershock = "shadowed",
    ancestral_portent = "soul_disease",
    ancestral_ambush = "soul_poison",
    haunting = "soulroot",
    faulted = "tree_seared",
    inhibited = "wraith",

    etched_fear = "sealing_square",
    etched_joy = "sealing_triangle",
    etched_disgust = "sealing_circle",
    sonder = "lemniscate",

    remorse = "seduction",
    bile_covered = "airwreath",
    inoculated = "imbued",
    frostbite = "direfrost",
    excess_melancholic = "thunderbrand",
    pheromones = "malevolence",
    excess_choleric = "emberbrand",
    contrition = "temptation",
    undertow = "quicksand",
    fungal_invasion = "impeded",
    coagulated_toxins = "corsin_weight",
    excess_phlegm = "frostbrand",
    mystified = "voidtrapped",
    kneel = "psi_tether",
    fragments = "vinethorns",

    preymark = "shadowbrand",
    fog_snared = "sand_trapped",
    causality = "omen",
    woe_curse = "shadowsphere",
}