local SkillMirrors = {
    Humourism = "Elemancy",
    Esoterica = "Arcanism",
    Hematurgy = "Thaumaturgy",
};

NU.skillMirrors = table.union(NU.skillMirrors, SkillMirrors);

-- TODO: Fix Ascendril BB mirrors.
NU.abMirrors.Humourism = {
    Retch = "Fireball",
    Implement = "Focus",
    Prowess = "Simultaneity",
    Tumult = "Whirlwind",
    Dissemble = "Snowstorm",
    Obliteration = "Shatter",
    Boil = "Ignite",
    Synapse = "Lightning",
    Perforate = "Icicle",
    Brimstone = "Firewhirl",
    Broil = "Scorch",
    Mist = "Fog",
    Cholerisk = "Efreeti",
    Parch = "Evaporate",
    Smother = "Conflagrate",
    Swathe = "Hailstorm",
    Overflow = "Flood",
    Uprising = "Torrent",
    Brainfreeze = "Coldsnap",
    Flense = "Frostblade",
    Revolt = "Gust",
    Traumatise = "Feedback",
    Equilibrium = "Pressurize",
    Stupor = "Thunder",
    Align = "Channel",
    Plunge = "Mistral",
    Frostbite = "Direfrost",
    Befoul = "Windlance",
    Oppress = "Cyclone",
}


NU.abMirrors.Esoterica = {
    Leaching = "Leaching",
    Triplicate = "Prism",
    Panoply = "Arcaneskin",
    Proscribe = "Dispel",
    Egress = "Soar",
    Embellish = "Chromatics",
    Forestall = "Countercurrent",
    Blear = "Mirage",
    Geminate = "Reflection",
    Clarity = "Clarity",
    Ascend = "Flight",
    Acumen = "Vivacity",
    Alluvion = "River",
    Sozedeti = "MirrorMastery",
    Mania = "Phantasm",
    Victimise = "Missiles",
    Enthrall = "Transfix",
    Indulge = "Manatap",
    Besmirch = "Mark",
    Runes = "Glyphs",
    Ensorcell = "Ensorcell",
    Illusion = "Illusion",
}


NU.abMirrors.Hematurgy = {
    Transfuse = "Harmony",
    Palpitate = "Flare",
    Primacy = "Quickcast",
    Circulate = "Windstorm",
    Fetter = "Adamance",
    Materialise = "Deliver",
    Actualise = "Catalyst",
    Descry = "Detect",
    Immerge = "Shift",
    Submerge = "Storage",
    Vein = "Restore",
    Profane = "Inferno",
    Arrhythmia = "Stall",
    ["Arrhythmia Release"] = "Stall Release",
    Congeal = "Calamity",
    Tendril = "Vortex",
    Saturate = "Anchor",
    Seep = "Blast",
    Contaminate = "Enrich",
    Aspects = "Resonance",
    Thrombosis = "Dissonance",
    Suffocate = "Typhoon",
    Resurface = "Push",
    Ablate = "Collapse",
    Forewarn = "Alert",
    Permeate = "Enrapture",
    Pulsate = "Eruption",
    Imbrue = "Maelstrom",
    Well = "Fulcrum",
}

