local SkillMirrors = {
    Gravitation = "Sporulation",
    Sciomancy = "Malediction",
    Sorcery = "Runecarving",
};

NU.skillMirrors = table.union(NU.skillMirrors, SkillMirrors);

NU.abMirrors.Gravitation = {
    Singularity = "Germinate",
    Stellar = "Enveloping",
    Featherstep = "Carpet",
    Recall = "Transplant",
    Massive = "Consumptive",
    Home = "Dispersal",
    Grip = "Ensnare",
    Remove = "Rot",
    Stability = "Furyscale",
    Absorb = "Stormstem",
    Attunement = "Ravencap",
    Collapse = "Omophagia",
    Pulsar = "Greycrown",
    Orbital = "Host",
    Collision = "Burst",
    Intermediate = "Festering",
    Imbue = "Inoculation",
    Cannon = "Mortify",
    Supermassive = "Putrefactive",
    Tether = "Clutchgill",
    Secure = "Rootcrest",
    Reverse = "Uplift",
    Weight = "Hartsblood",
    Genesis = "Colonisation",
    Advance = "Encroach",
    Impede = "Infect",
    Erupt = "Degrade",
    Horizon = "Sapmantle",
}

NU.abMirrors.Sciomancy = {
    Repay = "Obeisance",
    Nightsight = "Nightsight",
    Consume = "Mortis",
    Forgive = "Nourish",
    Shadowsphere = "Woe",
    Focus = "Implement",
    Haunt = "Vilipend",
    Mantle = "Preserve",
    Channel = "Meridian",
    Shadowprice = "Spiritpact",
    Purity = "Tenebrosity",
    Blast = "Maledict",
    Shadeling = "Myconid",
    Chill = "Numb",
    Shaderot = "Revile",
    Voidgaze = "Mystify",
    Engulf = "Stalk",
    Scourge = "Jinx",
    Gloom = "Despair",
    Leech = "Renewal",
    Hew = "Imperil",
    Ruin = "Enervate",
    Morph = "Imitate",
    Shadowbrand = "Preymark",
    Devour = "Assuage",
    Falter = "Anathemise",
    Fever = "Malady",
}


NU.abMirrors.Sorcery = {
    Phantasm = "Horizon",
    Arrogance = "Arrogance",
    Mirage = "Obfuscate",
    Slumber = "Slumber",
    Blurring = "Ironbark",
    Gravity = "Gravity",
    Flight = "Windwalk",
    Mark = "Quarry",
    Addling = "Addling",
    Rigor = "Prowess",
    Observation = "Observation",
    Soar = "Stormcloud",
    Irritation = "Irritation",
    Replicate = "Replicate",
    Dispel = "Unveil",
    Sagacity = "Mysticism",
    Glyphs = "Runes",
    Transfix = "Bewitch",
    Portal = "Portal",
    MirrorMastery = "Legerdemain",
    Chromatics = "Majesty",
    Attunement = "Attunement",
    Madness = "Lunacy",
    Ensorcell = "Enliven",
    Spellguard = "Sanctuary",
    Labyrinth = "Labyrinth",
    Destruction = "Destruction",
    Spectre = "Toil",
    Manatap = "Orison",
    Insanity = "Insanity",
    Illusion = "Deceive",
    Reflection = "Branch",
}

