local SkillMirrors = {
    Alchemy = "Primality",
    Experimentation = "Shamanism",
    Botany = "Naturalism",
};

NU.skillMirrors = table.union(NU.skillMirrors, SkillMirrors);

NU.abMirrors.Alchemy = {
    Conduit = "Quarterstaff",
    Volatility = "Communication",
    Static = "Lightning",
    Recall = "Recall",
    Clarify = "Squall",
    Catalyse = "Boosting",
    Corrosive = "Leafstorm",
    Virulent = "Vinelash",
    Upset = "Slam",
    Intrusive = "Vitiate",
    Electroshock = "Overload",
    Incendiary = "Discharge",
    Malignant = "Scourge",
    Discorporate = "Reclamation",
    Fulmination = "Stormbolt",
    Neurotic = "Sporulation",
    Overcharge = "Chainlightning",
    Condensate = "Cloudcall",
    Currents = "Staticburst",
    ["Currents Catalysed"] = "Staticburst Boosted",
    Resuscitation = "Lifebloom",
    Parity = "Equivalence",
    Infiltrative = "Infest",
    Rousing = "Effusion",
    Pathogen = "Spines",
    Asphyxiant = "Strangle",
    Accelerant = "Quicken",
    Preparation = "Naturaltide",
}

NU.abMirrors.Experimentation = {
    Extispicy = "Bonecasting",
    Ignition = "Harrowing",
    Obfuscation = "Protection",
    Dissolution = "Exorcise",
    Gasmask = "Spiritmask",
    Crutch = "Warding",
    Cognisance = "Divination",
    Disciplines = "Oaths",
    Prognosis = "Spiritsight",
    Expeditions = "Songlines",
    Lifevision = "Lifevision",
    Delegation = "Voyage",
    Hallucinogen = "Premonition",
    Causality = "Omen",

    Lacerating = "Cougar",
    Requesting = "Familiar",
    Transfusion = "Invigorate",
    Wailing = "Raven",
    Toxic = "Serpent",
    Preservation = "Tethering",
    Articulation = "Voice",
    Witness = "Glance",
    Arachnidal = "Spider",
    Interposition = "Spiritbond",
    Tumefactive = "Bear",
    Immolative = "Wyvern",
    Reconfiguration = "Morph",

    Compounds = "Fetishes",
    Exposure = "Attunement",
    Augmentation = "Stringing",
    Exhilarant = "Horn",
    Toxoid = "Ice",
    Invigorant = "Tooth",
    Caustic = "Bone",
    Anticoagulant = "Claw",
    Diagnostic = "Eye",
    Anesthetic = "Bark",
    Inhibiting = "Stone",
    Intoxicant = "Shell",
    Galvanic = "Feather",
}

NU.abMirrors.Botany = {
    Lift = "Elevate",
    Diffuse = "Emergence",
    Camouflage = "Blending",
    Quills = "Thorncoat",
    Subversion = "Panacea",
    Sterilisation = "Rejuvenate",
    Pheromones = "Malevolence",

    Assessment = "Perceive",
    Claim = "Imprint",
    Dismantle = "Sever",
    Surveil = "Look",
    Barricade = "Cage",
    Dictation = "Whisper",
    Reconnaissance = "Eyes",
    Specimen = "Fertility",
    Withdraw = "Return",
    Fecundity = "Everbloom",
    Consultation = "GroveFlow",
    Collaboration = "Linking",
    Selfdestruct = "Annihilation",

    Recede = "Release",
    Blight = "Overgrowth",
    Interlopers = "TRrespassers",
    Containment = "Canopy",
    Clutching = "Roots",
    Frequencies = "Screen",
    Bloodsap = "Thornwall",
    Distractions = "Whispers",
    Wander = "Flow",
    Alluring = "Pulling",
    Curtail = "Hinder",
    Fronds = "Animation",
    Propagate = "Surge",
    Medicinal = "Renewal",
    Perspective = "Displacement",
    Decompose = "Consumption",
    Envelop = "Barrier",
    Blightbringer = "Greenfoot",
}