local SkillMirrors = {
    Terramancy = "Tidebreaking",
    Animation = "Synthesis",
    Desiccation = "Inundation",
};

NU.skillMirrors = table.union(NU.skillMirrors, SkillMirrors);

NU.abMirrors.Terramancy = {
    Formation = "Bounty",
    Absorb = "Yearn",
    Stonebind = "Encrust",
    Surefooted = "Sealegs",
    Entwine = "Wavebreak",
    Stoneblast = "Riptide",
    Resonance = "Shore",
    Tremorsense = "Currents",
    Stonefury = "Rime",
    Grasp = "Spout",
    Rockshower = "Bedrabble",
    Merge = "Aquifer",
    Quake = "Undulation",
    Erosion = "Brume",
    Runemark = "Daub",
    Earthenpass = "Rivulets",
    Chasm = "Drown",
    Impale = "Harpoon",
    Steady = "Lowtide",
    Ricochet = "Flux",
    Stonevice = "Eviscerate",
    Tomb = "Trench",
    Momentum = "Hightide",
    Earthenwill = "Engulf",
    Shockwave = "Capsize",
    Earthenform = "Permafrost",

    Batter = "Clobber",
    Slam = "Crack",
    Facesmash = "Crest",
    Gutsmash = "Ram",
    Fracture = "Buckle",
    Furor = "Pitch",
    Overhand = "Breach",
    Pulp = "Wreck",
    Barrage = "Broadside",
    Skullbash = "Gybe",
    Hammer = "Keelhaul",
}

NU.abMirrors.Animation = {
    Animate = "Synthesise",
    Instruct = "Direct",
    Imprinting = "Enhancements",
    Erasure = "Excise",
    Movement = "Movement",
    Earthpaint = "Imbuing",
    Listening = "Listening",
    Escape = "Escape",
    Glance = "Glance",
    Priority = "Designate",
    Recover = "Recuperate",
    Bodylink = "Mouthpiece",
    Memory = "Modes",
    Servant = "Attend",
    Twinsoul = "Lifebond",
    Intertwine = "Amalgamate",
    Vigilance = "Ingrain",

    Strike = "Club",
    Heartpunch = "Trammel",
    Rip = "Squeeze",
    Wrack = "Chime",
    Shout = "Concuss",
    Grapple = "Nullify",
    Shatter = "Clutch",
    Pummel = "Pound",
    Choke = "Strangulate",
    Wrench = "Deconstruct",

    Knockdown = "Detain",
    Corner = "Enclose",
    Fend = "Guard",
    Airguard = "Cover",
    Rattle = "Reprisal",
    Prop = "Brace",
    Cycling = "Circuits",
    Shake = "Occlude",
    Kneeshatter = "Hobble",
    Steadfast = "Ballast",
}

NU.abMirrors.Desiccation = {
    Scour = "Hydrate",
    Flood = "Inundate",
    Sandwalk = "Drift",
    Surge = "Swell",
    Trap = "Snare",
    Presences = "Intruders",
    Regeneration = "Convalescence",
    Ruminate = "Revel",
    Sandstorm = "Apparition",
    Concealment = "Obscure",
    Dominion = "Negate",
    Shift = "Switch",
    Disturbances = "Fluctuations",
    Blast = "Hail",
    Simoon = "Chase",
    Distort = "Effervesce",
    Shield = "Harden",
    Swelter = "Sirensong",
    Confound = "Befuddle",
    Projection = "Panoptic",
    Wave = "Ebb",
    Instability = "Murk",
    Spikes = "Stalagmites",
    Harshen = "Delirium",
    Desert = "Fogbank",
    Whirl = "Gyre",
    Meld = "Subsume",
    Pillar = "Glacier",

    Whip = "Gnash",
    Scourge = "Unseen",
    Slice = "Abyss",
    Shred = "Feelers",
    Curse = "Terrors",
    Quicksand = "Undertow",
}