AUTOBASH.aggroMap["Dun Fortress"] = {
    [ [[an ogre sentry]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Daeron the Advisor]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a slime-encrusted spitter]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a demonic screamer]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a dangerous water snake]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an Orc archer]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a large catfish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an Orc guard]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an ogre cook]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an orc cook]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an Orc soldier]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Tolonar, Prince of the Dun Valley]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a drunk orc]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a prisoner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an orc sergeant]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a serpentine blademistress]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Hudi, an Impish recruit]] ] = {aggro = false, priority = -1, flee = false},
};