AUTOBASH.aggroMap["Eftehl Island"] = {
    [ [[the Eftehl Knight]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a ghost of a castle kitchen worker]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a ghost of a castle guard]] ] = {aggro = true, priority = 4, flee = false},
    [ [[a large yellow-spotted lizard]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a drunk pirate]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a tanned pirate]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Irma, the ferrywoman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sleek hammerhead shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a lumbering ogre ghost]] ] = {aggro = true, priority = 4, flee = false},
    [ [[Nilrys]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a ghost of a castle servant]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a pirate guard]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a large sea turtle]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Burr, the pirate leader]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a spear-wielding pirate]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a steel-grey barracuda]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a vibrantly pink flamingo]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Jorun Eftehl]] ] = {aggro = false, priority = -1, flee = false},
};