AUTOBASH.aggroMap["Enorian"] = {
    [ [[Preceptor Merkava]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Arqeshi Illuminai]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Noravipi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Duamvi-bound Ascendril mage]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Gnome woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Ascendril apprentice]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a company of one hundred mounted knights]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Eddy, a hook-handed Mhun veteran]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Templar Quartermaster Marehk]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an apprentice woodcutter]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Old Man Gullface]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Hokra, an Arqeshi priest]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Liakarian villager]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Tlachinolli, the instructor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Mhun woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a prismatic moth]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Tenerahin Shohreh]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Nianvi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Zashi, the Troll barkeep]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Freydha Shipbreaker, the Dedicant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Qayanehe, Keeper of Lore]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Post Master Irok]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a dawn-crested duck]] ] = {aggro = false, priority = -1, flee = false},
    [ [[some children of Moghedu]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Xia, the Retired Elder]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Damarr "Dami" Threadbare]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Minufi, Student of Lore]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Norraere Longforge]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Gallea the Smith]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Latesh, a stout Mhun merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Natine, the lemonade vendor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Rhulin Glintspear, the Engineer]] ] = {aggro = false, priority = -1, flee = false},
    [ [[wards of Enorian]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a resolute, adult Slyphian mako shark]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Bem, the Archival page]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Qeltad Nij]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Aribeth]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Timothentesh, a Mhun merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Iernos, the Eidolon of Spirit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Ramneze, the Tidesage]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a cautious captain]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Imp woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Havav, a wiry Mhun veteran]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Jarvan, a scarred Xoran man]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an apprentice clothier]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tubby Orc Aspirant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Vesk the theologian]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an inky black training strawbeast]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Crusader Jermar, a wingless Templar Knight]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a rowdy Mhun boy]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Darxa, the Orc bartender]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Watcher Adheda]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Brenn, the Millwright]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a towering wall of flames]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Arkassa, Constable of Enorian]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Dhivtah, an Arqeshi priestess]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Kobold woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Anaxagor Davolmann, the veteran]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Maurice]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Grook woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Commander Verok]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Chalai, a stout Mhun merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a young thief with a badge]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a hulking Ogre guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Laasha Glintspear, the Temple smith]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Captain Duarne, of the Enorian Guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[First Mate Skint]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Dunixi, the bartender]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Mhun boy]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Qala]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Vigil maid]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Norr, the Tanner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a towering magical seal]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Braytal Haarfil]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Xineoq, a Satyr bard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wooden practice post]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Mister Shrift]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Vorgna Glintspear, the Temple locksmith]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a stately mare]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a noisy crowd]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Arqeshi town crier]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a large fire elemental]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wolf spider]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Atavian man]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a crowd of Trolls]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Grand Master Aeclan]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a stony-faced Mhun worker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a donkey]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a legion of the Il'ahji]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Doctor Vosenai]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Beck]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Nurse Assistance Brekha]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Horkval woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an awkwardly armoured chicken]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Everet]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Taruk, an Orc Templar]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Troll man]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a host of one hundred Akkari soldiers]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wanderer]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Tentesh, a resilient Mhun veteran]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Yofaigh Qefin]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Krue Harvedson, Steward of the Vigil]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a freeman Orc woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Mhun girl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Oolmi Olobi, the Merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a paradise bird]] ] = {aggro = false, priority = -1, flee = false},
};