AUTOBASH.aggroMap["general"] = {
    [ [[a barnacle-encrusted oyster]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a shadowy nightmare]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a baby rhino calf]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a diminutive nightingale]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an undead spellshaper]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Tsol'aa vampire wearing jade]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wyvern spirit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a vicious mahogany-furred warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a golden, well groomed Syll]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a ferocious icewyrm]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a misty grey mare]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Syssin Defender]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sublimely scaled, siderealist serpent]] ] = { aggro = false, priority = -1, flee = false },
    [ [[a large chest mimic]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a hellcat]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a silver warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a gold-marked temple warrior]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a lustrously-armored sprightly white mare]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a war-painted orel]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Ascendril battlemage]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a yellow warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a majestic white stag]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a carrion beetle]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tiny, horned beetle]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a clay golem]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a medium-sized, dark green taerilan]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a manic wereraven]] ] = {aggro = true, priority = 4, flee = false},
    [ [[a bear spirit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an imperious Consanguine guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a midnight black stallion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a staunch Golban of the Akkari Host]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a grizzled war bear]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a diminutive onyx dragonling]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a winged piglet]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a band of slaves]] ] = {aggro = false, priority = -1, flee = false},
    [ [[the Tyranny-imbued form of an abyssal stallion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fiery efreeti]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an oversized, mountable ant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a regal, white lion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fervent Minotaur recruit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an enormous white goose]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a thick-furred albino tiger]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sleek, ebon-scaled drakir]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a walking spider mine]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive cinderkin]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a brilliant white phoenix]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a powerful russet charger]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a guard of the Esterport watch]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a war turtle]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sprightly adolescent emu]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a unicorn]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an enormous snow-white spider]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a donkey]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a veiled ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive bone scorpion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tormented, subjugated soul]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a scavenging vulture]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a synthetic crystal elemental]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a moss-covered peryton]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an enormous three-tailed mezilkree]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a disease-ridden direwolf]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an onyx wyvern]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an incandescent angel of ineffable scrutiny]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a miniature ice elemental]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a frail Horkval priest]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a shifting, fiery salamander]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a red and white warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tattooed Utari Tidesage]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive violet scorpion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a star-touched peryton]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wrinkled ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a shadow-imbued war chariot drawn by a stygian feline]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Indorani scion of despair]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a giant pangolin]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a shadowed grey badger]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fell werewolf]] ] = {aggro = true, priority = 4, flee = false},
    [ [[an inky shadeling]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a slavering, berserk werebear]] ] = {aggro = true, priority = 4, flee = false},
    [ [[a bridled, brutish sabre-toothed abosvi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Sir Ambrose Gallant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a blue warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a scarred, pale warhorse]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a swarm of bone fragments]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Adjeh, a Guard of the Ecclesiarchy]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a foul creature of stitched parts]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a vast, pulsating Totem of Haern]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a radiant sapphire-hued guardian angel]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a swift, sabre-toothed abosvi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a domineering Carnifex Eidolon]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a flaming stallion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a mindless experiment]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an adorable aureate dog]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a gentle pony]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a many-eyed angel dipped in brilliant gold]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Zealot firebrand]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a huge, bright cyan taerilan]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a one-eyed ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a chromatic quetzal]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a green blob]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a mud-coated hippo]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a hulking, marked orgyuk]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a steadfast Templar]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a black and cream warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fiercely majestic eagle owl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a violaceous wyvern whelpling]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a velveteen viper of violently seething vermilion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a colossal Teradrim guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Northern guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a phoenix of corruption]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a frenzied wereboar]] ] = {aggro = true, priority = 4, flee = false},
    [ [[a fervent Human recruit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sleek, golden horse]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sable warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fervent Djeirani recruit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a blindfolded ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fervent Tsol'aa recruit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tan warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive riding orych]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a broad-backed, chitinous sarskit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an enormous male tlingor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a black rhinoceros]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a colossal, gossamer-winged dragonfly]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a scarred ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a monstrous, abysmal metal-plated ursine]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a crystalline arachnid]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a battle-scarred crow]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a white warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tiny hyriamah hatchling]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a cougar spirit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a chestnut warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a raven spirit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a masked ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a mahogany warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a miniature fire elemental]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a ravenous mimic chest]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an iridescent, hiemal qilin]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an astral diremoth]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an austerely-armored powerfully muscled drakir]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a cream warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sullen war ram]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a celestial tegalid]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an immense, flowering toad]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a white-cloaked gryphon]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an undead servant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Guard of the Ecclesiarchy]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a miniature bladespider]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a colossal, venantium-fortified war snail]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a stoic revenant knight]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive island tortoise]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a tattooed ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sprightly white mare]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a bespectacled ancestral simulacrum]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an orange warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a majestic gryphon]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a capricious astral feline]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an oversized toad]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a guardian angel]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Divinely-trained suicide mouse]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an innocent basilisk hatchling]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an armored alpaca]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive, shark-mutated warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an imposing Luminary]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a falcon]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a serpent spirit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a small monkey]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a jherzan Archivist]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a division of sycophants]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a grey-furred direwolf]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an earthen acolyte]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an eerie, armored pale stallion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an eidolon of the deep woods]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Cahir, a box-headed Havothi warhound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a shadowfire-wreathed manticore]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an ice-wreathed, spectral wolf]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fervent recruit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a heavily-fortified fox]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a pathfinder]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Spirean Sciomancer]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a misshapen, coal-smudged snowman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a shadow-embraced skeletal avian]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a fiery guardian angel]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a misty kelpie stallion]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wicked cholerisk]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a many-eyed angel dipped in gold]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a ravenous werecroc]] ] = {aggro = true, priority = 4, flee = false},
    [ [[a massive, armoured wyrm]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a starry-winged, vulpine peryton]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an austerely-armored massive black scorpion]] ] = {aggro = false, priority = -1, flee = false},
};