AUTOBASH.aggroMap["Riparium"] = {
    [ [[a school of fish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a moray eel]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a huge beluga sturgeon]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a powerful-looking swordfish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a large red crab]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a large blackfish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a hauntingly beautiful siren]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a striped sea krait]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a gelatinous polyp]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a mantaglow fish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a jet-black manta]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a fearsome tiger shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a translucent ghost]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Xahlen, the city guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a man-eating shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a large, deepwater salmon]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a plated ixthean]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an angler fish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a merman guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a giant octopus]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Hudi, an Impish recruit]] ] = {aggro = false, priority = -1, flee = false},
};