AUTOBASH.aggroMap["Tcanna Island"] = {
    [ [[a venomous bushmaster]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Horkvali butcher]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an ebon crow]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a long-billed toucan]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a brown and tan python]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a howler monkey]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a vicious copperhead snake]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a dark green alligator]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a white goose]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a ragged coyote]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a small ocelot]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a spotted jaguar]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a blue crab]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Michael, the ferryman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a scarlet macaw]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a white-tailed deer]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a bald eagle]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a spotted leopard]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a thick boa constrictor]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Troll guard]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an oversized tortoise]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Administrator Thufek]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a silverback gorilla]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a brown-furred bat]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a black bear]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a gray wolf]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a tailless Rajamala]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an enormous elephant]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a black and white badger]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Troll cook]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a striped tiger]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a large capybara]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a water buffalo]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a box jellyfish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a lithe cougar]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a diseased raccoon]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Nazetu officer]] ] = {aggro = false, priority = 4, flee = false},
};