AUTOBASH.aggroMap["the Welto Trench"] = {
    [ [[Krelg, a scarred Xoran mercenary]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a grey bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[Migick, a hardy Gnome miner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an overworked sailor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a brown hunter shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a great white hunter shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a storm-wing harpy]] ] = {aggro = true, priority = 1, flee = false},
    [ [[a spotted hunter shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a striped hunter shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a dire octopus]] ] = {aggro = false, priority = -1, flee = true},
    [ [[a stone crab]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a black bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[Captain Brita, the Bold]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a grey tiger shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a large, deep water fish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a giant manta ray]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a bronze bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a blacktip shark]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a spotted tiger shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a twin-fang coet]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a great white bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a black welto shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a striped welto shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a scarred bull shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a brown welto shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a scarred tiger shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a scarred hunter shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a deep water serpent]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a black tiger shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a striped bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a spotted bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a great white tiger shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a brown tiger shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a spotted welto shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a black hunter shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a great white welto shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a brown bull shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a bronze tiger shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a grey welto shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a bronze welto shark]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a menacing torvok]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a box jellyfish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a striped tiger shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a scarred welto shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a bronze hunter shark]] ] = {aggro = false, priority = 4, flee = false},
};