AUTOBASH.aggroMap["the Isle of Ollin"] = {
    [ [[a sharp-clawed Boru prowler]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Nikivie, the Syll tamer]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sounder of ten boars]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a diligent Boru harvester]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Rylta, priestess of the Boru]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Toblis, a coral covered Captain]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a docile boar]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Jhakor, the collector]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a massive black crab]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a stinking Nazetu soldier]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a boisterous Nazetu child]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a hissing Boru infant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a rotting Nazetu ghoul]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Lairzeecil, the boar farmer]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Nazetu streetwalker]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a blackened, ravenous shark]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a dark-furred, rabid boar]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a fiendish, tainted Syll]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a towering Nazetu guard]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Qhizri, the tanner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Kazarine, Ambassador of Ollin]] ] = {aggro = false, priority = -1, flee = false},
};