AUTOBASH.aggroMap["the Den of Shadows"] = {
    [ [[a black sidewinder]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a tan python]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a grey krait]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a grey cobra]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a white boa]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a black adder]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a brown adder]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a brown krait]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a white python]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a horribly-mutated experiment]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a white cobra]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a tan sidewinder]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a mutated child]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a brown boa]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a white sidewinder]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a tan boa]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a grey adder]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a tan krait]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a tan cobra]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a grey python]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a black python]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a black boa]] ] = {aggro = false, priority = 5, flee = false},
};