AUTOBASH.aggroMap["the Underbelly"] = {
    [ [[a ravenous skrell]] ] = {aggro = true, priority = 1, flee = false},
    [ [[a desiccated Utari zombie]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a grey-skinned skrell whelp]] ] = {aggro = false, priority = 2, flee = false},
    [ [[an erratic Tarpen cultist]] ] = {aggro = true, priority = 1, flee = false},
    [ [[an Utari cultist with grim facial markings]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Azra, the Torrid]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a dire, plagued rat]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a crawling, ravenous Aslinn ghast]] ] = {aggro = true, priority = 1, flee = false},
    [ [[a venomous skrell whelp]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a snarling vakmut hound]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a gigantic white rat]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a malnourished vakmut]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a gigantic black rat]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a feral vakmut]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a jagged Golban ghast]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a drooling zombie Tarpen]] ] = {aggro = false, priority = 3, flee = false},
    [ [[a glazed-eye zombie Aslinn]] ] = {aggro = true, priority = 1, flee = false},
    [ [[a mangy Caentoi cultist]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a massive grey rat]] ] = {aggro = true, priority = 2, flee = false},
    [ [[Cythris, the Red]] ] = {aggro = true, priority = -1, flee = false},
    [ [[a hunched, bone-fisted Golban zombie]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a slavering vakmut]] ] = {aggro = true, priority = 2, flee = false},
    [ [[a pale skrell whelp]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a massive, tan-shelled whelk]] ] = {aggro = true, priority = 1, flee = false},
    [ [[a hulking Ursal ghast]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Ratcatcher Boros]] ] = {aggro = false, priority = -1, flee = false},
};