AUTOBASH.aggroMap["the village of Gorshire"] = {
    [ [[Mayor Gorbert]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Gnome man]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Gnome sentry]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Headmistress Pavalmort]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a little Gnome boy]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Sinoi, the Weaver]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Willis the millworker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a portly Gnome sentry]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a deputy constable]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a pet pot-bellied pig]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Bruer the Miller]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Bencur the Innkeeper]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a little Gnome girl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Gnome woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a guard pig]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a posse of youthful Gnomes]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Durnun]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Juniper, the Horticulturist]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Bruenor, the Gnome smith]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Wizardress Tenobob]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a lithe weasel]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an extremely drunk gnome]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Fergil the Sheepherder]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an inquisitive Gnome magus]] ] = {aggro = false, priority = -1, flee = false},
};