AUTOBASH.aggroMap["the Liruma Crater"] = {
    [ [[a disfigured sheep]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a twitching, ylem-bathed Mitrine]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Xavin]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Illikaal]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Ehtias]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an irradiated hyena]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a malformed Ophidian woman]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Emhyra]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Markos]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Undirnath]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Mazzion]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Eliadon]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a feral, misshapen hare]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Xenaden]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Sryaen]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Valeria]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Iesid]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Jakarn]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a two-headed buffalo]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Sibatti]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Kalena]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Valorie]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Orhm]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Mjoll]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Inkh]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Benedicto]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Jhura]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Sheryni]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Nkala]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a deformed lynx]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Myrnma]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a horrifically deformed adventurer resembling Ulo]] ] = {aggro = false, priority = 4, flee = false},
};