AUTOBASH.aggroMap["the Shattered Vortex"] = {
    [ [[a pathfinder]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a bubonis]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a crazed indorani]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a humbug]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a chaos storm]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a reinforcement warrior of the aztob]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a soulmaster]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a chaos orb]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a minion of chaos]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a chaos worm]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a petrified treant]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a withered crone]] ] = {aggro = false, priority = 4, flee = false},
    [ [[an ethereal firelord]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a chimera]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a sharp-toothed gremlin]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a bloodleech]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Sciomancer mage]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a dervish]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a chaos hound]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a simpering Sycophant]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a warped indorani]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a strained indorani]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a green slime]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a warped turtle]] ] = {aggro = false, priority = 4, flee = false},
};