AUTOBASH.aggroMap["the Port City of Delve"] = {
    [ [[a robed Ursal acolyte]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sentry of the Wards]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Khash Blacktongue]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Tuiln, leader of the Ashtani Resistance]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a grizzled Tarpen sailor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Dombler, the Trade Master]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Anstir, Captain of the Exchange Guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Apprentice Latrec Bresem]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Kray Ervenn]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Haakon Blacktooth]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Tithyen, Guardian of the Halls]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a solemn Golban acolyte]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a squadron of one hundred Delve infantry]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a slender Utari girl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Chelal, a flower seller]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an enthusiastic Caentoi merrymaker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Sonam Oevai]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Exchequer Monawe]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Wahelei, Lord-Provost of Delve]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a muscular Ursal dockhand]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a dark-eyed Utari woman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Hamal, Acolyte of Muadi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Jyoti Malhotra]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Utari scout]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Sasangka]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a large brute of a Caentoi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Bruut, Hand of the Helm]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Hruan, Guardian of the Halls]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Buhn Ironclaw]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a uniformed Exchange guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a ruffled-looking scientist]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Warden Syvar]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Salarin, a fruit merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Tarpen scientist]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a crowd of twelve thousand angry protesters]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Chantho, Watcher of the Silent Host]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a poorly dressed beggar girl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a crowd of nine thousand, seven hundred angry protesters]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Sauke, the swindler]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Onlethi Telakun, fisherman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Stonemason Gravi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Povic, the gambler]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a rotund Golba child]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a young Praexi acolyte]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Golba soldier]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a shabby-looking Caentoi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Caentoi merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a bloody-nosed prisoner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a contingent of forty Guards of the Ecclesiarchy]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Rokshush, a retired field surgeon]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a well-dressed Utari celebrant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Kathran, an aged hunter]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sailor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a well-dressed prisoner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Hemlik, a merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a burly Golban merrymaker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a scrawny beggar girl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Zelou Mitherat, silkmistress]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a pale-faced astronomer]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a recovering Golban child]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a stalwart Ursal acolyte]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a good-looking beggar girl]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Mamsell Sangbira]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Jarrga, the Docklands Harbormaster]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Utishimal, the pot maker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a sly-looking Caentoi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a resistance recruit]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Andaka]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Brother Bolan]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Enath, a Caentoi merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Varaq Atraing, hawker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a stern receptionist]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Utari researcher]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a muscled Caentoi citizen]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Scrivener Talas]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a lithe Utari dockhand]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Aieriallia, Eld of the Twilight]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a filthy prisoner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Ursal fighter]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Zayzala, a richly-dressed merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a conspicuous street scamp]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Captain Guul Rog]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Merchant Jyran]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a rowdy Tarpen celebrant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Netia Ironhand]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Iarsis, Acolyte of Dejaani]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Vrin Sokersi, Sentinel of the Auric Guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Jirac Ervenn]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Gifol Linet, Researcher of the Society]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a wiry Caentoi knifemaker]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Ibram Nasser, High Priest of Muadi]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Aqurai, a Caentoi merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a young Tarpen scholar]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Dalturia "Ironmonger" Najar]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Tinkerer Barakin Sho'vej]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a weary Golba soldier]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an Ursal citizen]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Dal, an Utari sailor]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a rough street urchin]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Golban guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a weary prisoner]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a Caentoi commander]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Yoti, a hulking Utari dockhand]] ] = {aggro = false, priority = -1, flee = false},
    [ [[a uniformed Dockland guard]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Exciseman Wanduluu]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Ood, a fat Caentoi merchant]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Hannis, a Tarpen researcher]] ] = {aggro = false, priority = -1, flee = false},
    [ [[an elderly Utari citizen]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Onthian Telakun, fisherman]] ] = {aggro = false, priority = -1, flee = false},
    [ [[Lysadri, an esteemed Caentoi Madam]] ] = {aggro = false, priority = -1, flee = false},
};