AUTOBASH.aggroMap["Tiyen Esityi"] = {
    [ [[a Nazetu crossbowman]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Lieutenant Gharvoi]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a crazed Nazetu cutter]] ] = {aggro = false, priority = 1, flee = false},
    [ [[Quartermaster Kuius]] ] = {aggro = false, priority = 2, flee = false},
    [ [[insubstantial whispers]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Commander Marakhi]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a Nazetu necromancer]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a tangible malevolence]] ] = {aggro = false, priority = 2, flee = false},
    [ [[Lieutenant Chiakhi]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a Nazetu cook]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a mutated Nazetu intercessor]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a massive, sacred serpent]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a Nazetu halberdier]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Nazetu captain]] ] = {aggro = false, priority = 5, flee = false},
    [ [[a victimised intruder]] ] = {aggro = false, priority = 5, flee = false},
    [ [[the creature beneath Tiyen Esityi]] ] = {aggro = true, priority = -1, flee = false},
    [ [[a ball of chitinous legs]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a cancerous stallion]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Nazetu corrupter]] ] = {aggro = false, priority = 4, flee = false},
    [ [[Tirahl the Necromancer]] ] = {aggro = false, priority = 2, flee = false},
    [ [[a bound shade]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a supply officer]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a deformed Nazetu priest]] ] = {aggro = false, priority = 4, flee = false},
    [ [[a Nazetu provost]] ] = {aggro = false, priority = 4, flee = false},
};